export const menuArray = [
  {
    name: "Quinoa Bowl",
    ingredients: ["quinoa", "grilled chicken", "mixed vegetables", "avocado"],
    price: 12,
    emoji: "🍲",
    id: 0,
    isOrdered: false,
    uuid: "notSet",
  },
  {
    name: "Acai Bowl",
    ingredients: ["acai", "granola", "mixed berries", "honey"],
    price: 9,
    emoji: "🥣",
    id: 1,
    isOrdered: false,
    uuid: "notSet",
  },
  {
    name: "Kale Salad",
    ingredients: ["kale", "quinoa", "avocado", "feta cheese"],
    price: 10,
    emoji: "🥗",
    id: 2,
    isOrdered: false,
    uuid: "notSet",
  },
  {
    name: "Grilled Chicken Sandwich",
    ingredients: ["grilled chicken", "whole wheat bread", "lettuce", "tomato"],
    price: 11,
    emoji: "🥪",
    id: 3,
    isOrdered: false,
    uuid: "notSet",
  },
  {
    name: "Turkey Burger",
    ingredients: ["turkey patty", "whole wheat bun", "arugula", "red onion"],
    price: 12,
    emoji: "🍔",
    id: 4,
    isOrdered: false,
    uuid: "notSet",
  },
  {
    name: "Salmon Bowl",
    ingredients: [
      "grilled salmon",
      "brown rice",
      "mixed vegetables",
      "sesame seeds",
    ],
    price: 14,
    emoji: "🍲",
    id: 5,
    isOrdered: false,
    uuid: "notSet",
  },
  {
    name: "Veggie Wrap",
    ingredients: ["hummus", "mixed vegetables", "whole wheat wrap"],
    price: 8,
    emoji: "🌯",
    id: 6,
    isOrdered: false,
    uuid: "notSet",
  },
  {
    name: "Roasted Turkey Sandwich",
    ingredients: ["roasted turkey", "whole wheat bread", "cranberry sauce"],
    price: 10,
    emoji: "🥪",
    id: 7,
    isOrdered: false,
    uuid: "notSet",
  },
  {
    name: "Spinach Salad",
    ingredients: ["spinach", "strawberries", "walnuts", "goat cheese"],
    price: 9,
    emoji: "🥗",
    id: 8,
    isOrdered: false,
    uuid: "notSet",
  },
  {
    name: "Sweet Potato Fries",
    ingredients: ["sweet potato", "olive oil", "sea salt"],
    price: 5,
    emoji: "🍟",
    id: 9,
    isOrdered: false,
    uuid: "notSet",
  },
  {
    name: "Grilled Shrimp Skewers",
    ingredients: ["grilled shrimp", "mixed vegetables", "lemon"],
    price: 14,
    emoji: "🍢",
    id: 10,
    isOrdered: false,
    uuid: "notSet",
  },
  {
    name: "Hummus Plate",
    ingredients: ["hummus", "carrots", "celery", "pita bread"],
    price: 8,
    emoji: "🍽️",
    id: 11,
    isOrdered: false,
    uuid: "notSet",
  },
  {
    name: "Grilled Chicken Caesar Salad",
    ingredients: [
      "grilled chicken",
      "romaine lettuce",
      "parmesan cheese",
      "caesar dressing",
    ],
    price: 12,
    emoji: "🥗",
    id: 12,
    isOrdered: false,
    uuid: "notSet",
  },
  {
    name: "Vegan Burger",
    ingredients: ["vegan patty", "whole wheat bun", "guacamole", "lettuce"],
    price: 13,
    emoji: "🍔",
    id: 13,
    isOrdered: false,
    uuid: "notSet",
  },
];
